openscm/scmdata

- CHANGELOG.rst
- notebooks/scmdataframe.ipynb
- src/scmdata/dataframe.py
- tests/unit/test_dataframe.py
> Get unique meta convenience method

- MANIFEST.in
- setup.py
@lewisjared if we add this then I think we can make a conda installable package (then I can start working my way up the tree)
> Update setup.py and manifest.in

- CHANGELOG.rst
- src/scmdata/dataframe.py
Workaround for weird pandas bug when passing an empty dict of renames
cc @znicholls
> Only rename if needed

- docs/source/development.rst
> Add conda release instructions

- CHANGELOG.rst
- setup.py
- src/scmdata/time.py
> Remove scipy as a required dependency

- src/scmdata/filters.py
- src/scmdata/groupby.py
- src/scmdata/run.py
- src/scmdata/testing.py
- src/scmdata/timeseries.py
Notes from reading through #21
> Run refactor zn

- .codecov.yml
- CHANGELOG.rst
- README.rst
- docs/source/conf.py
- docs/source/data.rst
- docs/source/index.rst
- docs/source/scmdata.filters.rst
- docs/source/scmdata.groupby.rst
- docs/source/scmdata.run.rst
- docs/source/scmdata.testing.rst
- docs/source/scmdata.timeseries.rst
- notebooks/emissions-units-with-pint.ipynb
- notebooks/scmdataframe.ipynb
- setup.py
- src/scmdata/__init__.py
- src/scmdata/dataframe.py
- src/scmdata/groupby.py
- src/scmdata/netcdf.py
- src/scmdata/run.py
- src/scmdata/time.py
- src/scmdata/timeseries.py
- tests/unit/test_run.py
- tests/unit/test_timeseries.py
Adds documentation about how `ScmRun` works (I had to update a bunch of stuff to get it to behave).
> Add docs for run refactor

- CHANGELOG.rst
- Makefile
- src/scmdata/plotting.py
- tests/unit/test_plotting.py
> Hotfix install issues

- .github/workflows/test-conda-install.yml
- .github/workflows/test-pypi-install.yml
- CHANGELOG.rst
- README.rst
> Add conda install test

- CHANGELOG.rst
- src/scmdata/__init__.py
- src/scmdata/dataframe.py
- src/scmdata/run.py
- tests/conftest.py
- tests/unit/test_dataframe.py
- tests/unit/test_run.py
> Ref period refactor

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
> Add drop_meta

- src/scmdata/dataframe.py
- tests/unit/test_run.py
Add `time_axis` to ScmDataFrame.long_data
> Convenience time axes JL

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
> Use cftime when reindexing timeseries

- CHANGELOG.rst
- notebooks/scmdataframe.ipynb
- notebooks/time-operations.ipynb
- src/scmdata/dataframe.py
- tests/notebook-tests.cfg
- tests/unit/test_dataframe.py
> Deprecation warning if ScmDataFrame is used

- CHANGELOG.rst
- src/scmdata/filters.py
- src/scmdata/run.py
- tests/unit/test_run.py
> Convert unit hotfix

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
> Remove spurious warning in convert unit

- CHANGELOG.rst
- notebooks/scmrun.ipynb
- notebooks/time-operations.ipynb
- setup.py
- src/scmdata/errors.py
- src/scmdata/run.py
- tests/unit/test_run.py
> Fix meta duplication handling

- CHANGELOG.rst
- setup.py
- src/scmdata/offsets.py
- tests/unit/test_offsets.py
> Check business offsets using name instead of instance

- .github/workflows/ci-cd-workflow.yml
> Hotfix workflow

- .github/ISSUE_TEMPLATE/bug_report.md
> Hotfix bug report

- CHANGELOG.rst
- Makefile
- src/scmdata/run.py
- tests/unit/test_run.py
> Timeseries without nans

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
> Ignore missing columns

- CHANGELOG.rst
- Makefile
- notebooks/emissions-units-with-pint.ipynb
> Hotfix notebook

- CHANGELOG.rst
- setup.py
- tests/integration/test_scmrun_speed.py
> Add performance benchmarks

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
> Add na_override

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
- [x Documentation added (where applicable)
> Update default drop_meta behaviour to False

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- Makefile
- setup.py
- src/scmdata/ops.py
- tests/unit/test_ops.py
> Make scipy optional

- CHANGELOG.rst
- src/scmdata/groupby.py
- src/scmdata/run.py
- tests/unit/test_groupby.py
- tests/unit/test_run.py
> 7.0.0 hotfixes

- CHANGELOG.rst
- src/scmdata/run.py
- tests/unit/test_run.py
> Check the type of runs

- CHANGELOG.rst
- src/scmdata/filters.py
- src/scmdata/run.py
- tests/unit/test_run.py
> Empty filter edgecases

- .github/workflows/test-conda-install.yml
- CHANGELOG.rst
- Makefile
- notebooks/scmrun.ipynb
- setup.py
- src/scmdata/run.py
- src/scmdata/timeseries.py
- src/scmdata/units.py
> Update to new openscm-units

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- src/scmdata/ops.py
- tests/unit/test_plotting.py
- tests/unit/test_run.py
This picks up an error with our scipy import which is also fixed here.
```
```
> Add CI without seaborn installed

- CHANGELOG.rst
- src/scmdata/time.py
- tests/unit/test_timeseries_convertor.py
> Fix scipy lazy load

- CHANGELOG.rst
- src/scmdata/filters.py
- tests/unit/test_run.py
> Filter years with numpy array

- CHANGELOG.rst
- src/scmdata/run.py
- tests/integration/test_io.py
> Fix write read circularity

- CHANGELOG.rst
- src/scmdata/database.py
- tests/unit/test_database.py
> Database load from list

- .github/workflows/ci-cd-workflow.yml
- .github/workflows/test-conda-install.yml
- .github/workflows/test-pypi-install.yml
- CHANGELOG.rst
- setup.py
> Update CI workflow

- CHANGELOG.rst
- tests/unit/test_netcdf.py
> xarray msg is different for xarray<=0.16.1

- CHANGELOG.rst
- src/scmdata/__init__.py
> Removes REQUIRED_COLS variable

- src/scmdata/processing.py
> Add extra docs

- CHANGELOG.rst
- notebooks/processing.ipynb
- src/scmdata/processing.py
- tests/integration/test_processing.py
> Crossing times quantiles

- .github/workflows/ci-cd-workflow.yml
- .readthedocs.yml
- CHANGELOG.rst
- setup.cfg
> Add check of distribution creation to CI

- CHANGELOG.rst
- src/scmdata/__init__.py
This will require a version bump
> Use the right version

- CHANGELOG.rst
- src/scmdata/groupby.py
- src/scmdata/run.py
- tests/unit/test_groupby.py
- tests/unit/test_run.py
> Add apply function to ScmRun

- CHANGELOG.rst
- src/scmdata/run.py
Enhancement. 
Replaced Map with apply.
>  Replaced Map with apply

- CHANGELOG.rst
- setup.cfg
- src/scmdata/run.py
- tests/unit/test_run.py
> fix(scmrun): Fix filtering of time index for a empty ScmRun

- CHANGELOG.rst
- setup.cfg
- tests/integration/test_plotting_integration.py
- tests/unit/test_netcdf.py
- tests/unit/test_run.py
> Unpin numpy

- .readthedocs.yml
- CHANGELOG.rst
- Makefile
- docs/source/notebooks/README.md
- setup.cfg
> Remove jupytext server dependency

- .github/workflows/bump.yaml
- changelog/235.improvement.md
- changelog/235.trivial.md
- changelog/260.improvement.md
- changelog/267.trivial.md
- docs/source/changelog.md
- pyproject.toml
> Fix bump CI action

- changelog/268.trivial.md
- docs/source/api/scmdata.groupby.rst
- src/scmdata/groupby.py
- src/scmdata/run.py
- stubs/joblib.pyi
- tests/unit/test_groupby.py
> Refactor apply parallel
